#=========================================================================
# Parse gate-level power reports
#=========================================================================

name: parse-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - power.hier 

outputs:
  - overall.summary
  - power.summary
  - alu.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/power.hier outputs/overall.summary
  - python parse.py inputs/power.hier

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  flatten_effort: 0
  clock_period: 1.0
