#=========================================================================
# Parse gate-level power reports
#=========================================================================

name: parse-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - power.hier 

outputs:
  - power.summary
  - alu.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - python parse.py inputs/power.hier

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
