#=========================================================================
# Synopsys PTPX -- Gate-Level Power Estimation
#=========================================================================
# This step runs gate-level average power analysis with Synopsys PrimeTime
#
# Author : Christopher Torng
# Date   : March 3, 2020
#

name: synopsys-ptpx-gl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.pt.sdc
  - design.spef.gz
  - run.saif

outputs:
  - power.hier

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p reports logs
  - pt_shell -f ptpx.tcl | tee logs/pt.log
  - cp reports/{design_name}.power.hier.rpt outputs/power.hier

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  strip_path: th/dut


