name: testbench

outputs:
  - testbench.sv
  - test_vectors.txt
  - test_outputs.txt
  - design.args

commands:
  - ./run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  PWR_AWARE: True
