#=========================================================================
# Parse gate-level power reports
#=========================================================================

name: parse-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - power.hier 

outputs:
  - overall.summary
  - power.summary
  - alu.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
    #- python parse.py inputs/power.hier
  - cp inputs/power.hier outputs/overall.summary

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
